.. _py_learner_req:

Minimum requirements for learners
#################################

.. include:: /guide/learners/python/minimum_req.rst


.. _py_set_params:

Specifying learners and set hyperparameters
###########################################

.. include:: /guide/learners/python/set_hyperparams.rst

.. _py_tune_params:

Hyperparameter tuning
#####################

.. include:: /guide/learners/python/tune_hyperparams.rst


Hyperparameter tuning (Grid Search)
###################################

.. warning::
   **Deprecated:** The ``tune()`` method is deprecated and be removed in a future version.
   Please use ``tune_ml_models()`` for hyperparameter tuning, see :ref:`Hyperparameter tuning <py_tune_params>`.

.. include:: /guide/learners/python/tune_hyperparams_old.rst

.. _py_eval_learners:

Evaluate learners
#################

.. include:: /guide/learners/python/evaluate_learners.rst


.. _py_ext_pred:

Advanced: External Predictions
##############################


.. include:: /guide/learners/python/external_preds.rst