The following scores for difference-in-differences models are implemented.


.. _did-pa-score:

Panel Data
==========

.. include:: /guide/scores/did/did_pa_score.rst


.. _did-cs-score:

Repeated Cross-Sectional Data
=============================

.. include:: /guide/scores/did/did_cs_score.rst


Two treatment periods
=====================

.. warning::
    This documentation refers to the deprecated implementation for two time periods. 
    This functionality will be removed in a future version. The generalized version are :ref:`did-pa-score` and :ref:`did-cs-score`.


Panel Data
~~~~~~~~~~~

.. include:: /guide/scores/did/did_pa_binary_score.rst


Repeated Cross-Sectional Data
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


.. include:: /guide/scores/did/did_cs_binary_score.rst