The following difference-in-differences models implemented.

.. _sensitivity_did:

Difference-in-Differences for Panel Data
========================================

.. include:: /guide/sensitivity/did/did_sensitivity.rst


.. _sensitivity_did_cs:

Difference-in-Differences for repeated cross-sections
=====================================================

.. include:: /guide/sensitivity/did/did_cs_sensitivity.rst
