.. _r_learner_req:

Minimum requirements for learners
#################################

.. include:: /guide/learners/r/minimum_req.rst


.. _r_set_params:

Specifying learners and set hyperparameters
###########################################

.. include:: /guide/learners/r/set_hyperparams.rst


.. _r_pipelines:

Using pipelines to construct learners
#####################################

.. include:: /guide/learners/r/pipelines.rst


.. _r_tune_params:

Hyperparameter tuning
#####################

.. include:: /guide/learners/r/tune_hyperparams.rst


.. _r_tune_and_pipelines:

Hyperparameter tuning with pipelines
####################################

.. include:: /guide/learners/r/tune_and_pipelines.rst

