FROM ubuntu:24.04

# Set non-interactive mode to avoid prompts
ENV DEBIAN_FRONTEND=noninteractive

# Update package list and install dependencies
RUN apt-get update && \
    apt-get install -y \
    software-properties-common \
    graphviz \
    wget \
    dirmngr \
    gnupg \
    apt-transport-https \
    ca-certificates \
    git \
    cmake

# Install locale packages
RUN apt-get update && \
    apt-get install -y locales && \
    locale-gen en_US.UTF-8 && \
    update-locale LANG=en_US.UTF-8

# Set environment variables for locale
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# Install Python 3.12
RUN add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.12 python3.12-venv python3.12-dev python3-pip python3-full && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Set Python 3.12 as the default for both python and python3
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1 && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3.12 1

# Add R repository and install R
RUN wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | tee /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc && \
    add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu noble-cran40/' && \
    apt-get update && \
    apt-get install -y r-base r-base-dev zlib1g-dev libicu-dev pandoc make libcurl4-openssl-dev libssl-dev

# Install Python packages
COPY requirements.txt /tmp/requirements.txt
RUN python -m venv /workspace/.venv && \
    /workspace/.venv/bin/python -m pip install --upgrade pip && \
    /workspace/.venv/bin/pip install -r /tmp/requirements.txt

# Set the virtual environment as the default Python environment
ENV PATH="/workspace/.venv/bin:$PATH"

# Install from main branch of DoubleML for Python
RUN pip uninstall -y DoubleML && \
    pip install git+https://github.com/DoubleML/doubleml-for-py.git@main#egg=DoubleML[rdd]

# Create a directory for R user libraries and set the default R user library path
RUN mkdir -p /usr/local/lib/R/site-library
ENV R_LIBS_USER=/usr/local/lib/R/site-library

# Install R packages and Jupyter kernel
RUN Rscript -e "install.packages('remotes')" && \
    Rscript -e "remotes::install_github('DoubleML/doubleml-for-r', dependencies = TRUE)" && \
    Rscript -e "install.packages(c('ggplot2', 'IRkernel', 'xgboost', 'hdm', 'reshape2', 'gridExtra', 'igraph', 'mlr3filters', 'mlr3measures', 'did', dependencies=TRUE))" && \
    Rscript -e "IRkernel::installspec()"

# Set the working directory
WORKDIR /workspace
