The following scores for nonparametric regression models are implemented.

.. _irm-score:

Binary Interactive Regression Model (IRM)
==========================================

.. include:: /guide/scores/irm/irm_score.rst


.. _apo-score:

Average Potential Outcomes (APOs)
=================================

.. include:: /guide/scores/irm/apo_score.rst
 

.. _iivm-score:

Interactive IV model (IIVM)
===========================

.. include:: /guide/scores/irm/iivm_score.rst


.. _pq-score:

Potential quantiles (PQs)
=========================

.. include:: /guide/scores/irm/pq_score.rst


.. _lpq-score:

Local potential quantiles (LPQs)
================================

.. include:: /guide/scores/irm/lpq_score.rst


.. _cvar-score:

Conditional value at risk (CVaR)
================================

.. include:: /guide/scores/irm/cvar_score.rst