The following scores for partially linear models are implemented.

.. _plr-score:

Partially linear regression model (PLR)
=======================================

.. include:: /guide/scores/plm/plr_score.rst

.. _lplr-score:

Logistic partial linear regression (LPLR)
===========================================

.. include:: /guide/scores/plm/lplr_score.rst

.. _plpr-score:

Partially linear panel regression (PLPR)
========================================

.. include:: /guide/scores/plm/plpr_score.rst

.. _pliv-score:

Partially linear IV regression model (PLIV)
===========================================

.. include:: /guide/scores/plm/pliv_score.rst
