# Workflow based on https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

name: Deploy Docu (stable)

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo containing the docu source
      uses: actions/checkout@v4

    - name: Install graphviz
      run: sudo apt-get install graphviz

    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies and the python package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install R
      uses: r-lib/actions/setup-r@v2

    - name: Query R version
      run: |
        writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
      shell: Rscript {0}

    - name: Install R kernel for Jupyter and the R package DoubleML (dev)
      run: |
        install.packages('remotes')
        remotes::install_cran('DoubleML', dependencies = TRUE)
        install.packages(c('ggplot2', 'IRkernel', 'xgboost', 'hdm', 'reshape2', 'gridExtra', "igraph", "mlr3filters", "mlr3measures", "did"))
        IRkernel::installspec()
      shell: Rscript {0}

    - name: Build docu with sphinx
      run: |
        make -C doc html # build docu

    - name: Deploy to stable
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        repository-name: DoubleML/doubleml.github.io
        branch: main
        folder: doc/_build/html
        target-folder: stable
        git-config-name: DoubleML Deploy Bot
        git-config-email: DoubleML@users.noreply.github.com
        clean: true
        ssh-key: ${{ secrets.DEPLOY_KEY }}
