# Workflow based on https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

name: Deploy Docu (dev)

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      doubleml-py-branch:
        description: 'Branch in https://github.com/DoubleML/doubleml-for-py'
        required: true
        default: 'master'
      doubleml-r-branch:
        description: 'Branch in https://github.com/DoubleML/doubleml-for-r'
        required: true
        default: 'master'
  schedule:
    - cron: "0 9 * * 1,3,5"


jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Check out the repo containing the docu source
      uses: actions/checkout@v2

    - name: Check out the repo containing the python pkg DoubleML (dev)
      if: ${{ github.event_name != 'workflow_dispatch' }
      uses: actions/checkout@v2
      with:
        repository: DoubleML/doubleml-for-py
        path: doubleml-for-py

    - name: Check out the repo containing the python pkg DoubleML (dev)
      if: ${{ github.event_name == 'workflow_dispatch' }
      uses: actions/checkout@v2
      with:
        repository: DoubleML/doubleml-for-py
        path: doubleml-for-py
        ref: ${{ github.event.inputs.doubleml-py-branch }}

    - name: Install SSH Client for deploying the docu to github pages
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Install graphviz
      run: sudo apt-get install graphviz

    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies and the python package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip uninstall -y DoubleML
        cd doubleml-for-py
        pip install -e .

    - name: Add R repository
      run: |
        sudo apt install dirmngr gnupg apt-transport-https ca-certificates software-properties-common
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
        sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'
    - name: Install R
      run: |
        sudo apt-get update
        sudo apt-get install r-base
        sudo apt-get install r-base-dev
        sudo apt-get install -y zlib1g-dev libicu-dev pandoc make libcurl4-openssl-dev libssl-dev

    - name: Get user library folder
      run: |
        mkdir ${GITHUB_WORKSPACE}/tmp_r_libs_user
        echo R_LIBS_USER=${GITHUB_WORKSPACE}/tmp_r_libs_user >> $GITHUB_ENV

    - name: Query R version
      run: |
        writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
      shell: Rscript {0}

    - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: ${{ env.R_LIBS_USER }}
        key: doubleml-user-guide-dev-${{ hashFiles('.github/R-version') }}

    - name: Install R kernel for Jupyter and the R package DoubleML (dev)
      if: ${{ github.event_name != 'workflow_dispatch' }
      run: |
        install.packages('remotes')
        remotes::install_github('DoubleML/doubleml-for-r', dependencies = TRUE)
        install.packages(c('ggplot2', 'IRkernel', 'xgboost'))
        IRkernel::installspec()
      shell: Rscript {0}

    - name: Install R kernel for Jupyter and the R package DoubleML (dev)
      if: ${{ github.event_name == 'workflow_dispatch' }
      run: |
        install.packages('remotes')
        remotes::install_github('DoubleML/doubleml-for-r@${{ github.event.inputs.doubleml-r-branch }}', dependencies = TRUE)
        install.packages(c('ggplot2', 'IRkernel', 'xgboost'))
        IRkernel::installspec()
      shell: Rscript {0}

    - name: Build docu with sphinx
      run: |
        make -C doc html # build docu

    - name: Deploy to dev
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        REPOSITORY_NAME: DoubleML/doubleml.github.io
        BRANCH: master
        FOLDER: doc/_build/html
        TARGET_FOLDER: dev
        GIT_CONFIG_NAME: DoubleML Deploy Bot
        GIT_CONFIG_EMAIL: DoubleML@users.noreply.github.com
        CLEAN: true
        SSH: true
