# Workflow based on https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

name: Test Docu Build (with dev pkgs)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      doubleml-py-branch:
        description: 'Branch in https://github.com/DoubleML/doubleml-for-py'
        required: true
        default: 'main'
      doubleml-r-branch:
        description: 'Branch in https://github.com/DoubleML/doubleml-for-r'
        required: true
        default: 'main'
  schedule:
    - cron: "0 9 * * 1,3,5"


jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Check out the repo containing the docu source
      uses: actions/checkout@v4

    - name: Check out the repo containing the python pkg DoubleML (dev)
      if: ${{ github.event_name != 'workflow_dispatch' }}
      uses: actions/checkout@v4
      with:
        repository: DoubleML/doubleml-for-py
        path: doubleml-for-py

    - name: Check out the repo containing the python pkg DoubleML (dev)
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/checkout@v4
      with:
        repository: DoubleML/doubleml-for-py
        path: doubleml-for-py
        ref: ${{ github.event.inputs.doubleml-py-branch }}

    - name: Install graphviz
      run: sudo apt-get install graphviz

    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install R
      uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2

    - name: Query R version
      run: |
        writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
      shell: Rscript {0}

    - name: Install R kernel for Jupyter and the R package DoubleML (dev)
      if: ${{ github.event_name != 'workflow_dispatch' }}
      run: |
        install.packages('remotes')
        remotes::install_github('DoubleML/doubleml-for-r', dependencies = TRUE)
        install.packages(c('knitr', 'ggplot2', 'IRkernel', 'xgboost', 'hdm', 'reshape2', 'gridExtra', "igraph", "mlr3filters", "mlr3measures", "did"))
        IRkernel::installspec()
      shell: Rscript {0}

    - name: Install R kernel for Jupyter and the R package DoubleML (dev)
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        install.packages('remotes')
        remotes::install_github('DoubleML/doubleml-for-r@${{ github.event.inputs.doubleml-r-branch }}', dependencies = TRUE)
        install.packages(c('knitr', 'ggplot2', 'IRkernel', 'xgboost', 'hdm', 'reshape2', 'gridExtra', "igraph", "mlr3filters", "mlr3measures", "did"))
        IRkernel::installspec()
      shell: Rscript {0}
    
    - name: Build docu with sphinx
      run: |
        make -C doc html # build docu

    - name: Check for broken links / URLs
      run: |
        make -C doc linkcheck

    - name: Upload html artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build_html
        path: doc/_build/html/
