# Workflow based on https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

name: Test Docu Build (with released pkgs)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1,3,5"


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo containing the docu source
      uses: actions/checkout@v4

    - name: Install graphviz
      run: sudo apt-get install graphviz

    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies and the python package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install R
      uses: r-lib/actions/setup-r@v2
    
    - name: Query R version
      run: |
        writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
      shell: Rscript {0}
    
    - name: Install pandoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: Install R kernel for Jupyter and the R package DoubleML (CRAN release)
      run: |
        install.packages('remotes')
        remotes::install_cran('DoubleML', dependencies = TRUE)
        install.packages(c('knitr', 'ggplot2', 'IRkernel', 'xgboost', 'hdm', 'reshape2', 'gridExtra', "igraph", "mlr3filters", "mlr3measures", "did"))
        IRkernel::installspec()
      shell: Rscript {0}

    - name: Build docu with sphinx
      run: |
        make -C doc html # build docu

    - name: Check for broken links / URLs
      run: |
        make -C doc linkcheck

    - name: Upload html artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build_html
        path: doc/_build/html/
