# Workflow based on https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

name: Test Docu Build (with dev pkgs)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      doubleml-py-branch:
        description: 'Branch in https://github.com/DoubleML/doubleml-for-py'
        required: true
        default: 'main'
      doubleml-r-branch:
        description: 'Branch in https://github.com/DoubleML/doubleml-for-r'
        required: true
        default: 'main'
      nbsphinx-execute:
        description: 'Execute notebooks with nbsphinx'
        required: false
        default: 'auto'
  schedule:
    - cron: "0 9 * * 1,3,5"


jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: svenklaassen/doubleml-docs:latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Check out the repo containing the docu source
      uses: actions/checkout@v4

    - name: Check out the repo containing the python pkg DoubleML (main branch)
      if: ${{ github.event_name != 'workflow_dispatch' }}
      uses: actions/checkout@v4
      with:
        repository: DoubleML/doubleml-for-py
        path: doubleml-for-py

    - name: Check out the repo containing the python pkg DoubleML (custom branch)
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/checkout@v4
      with:
        repository: DoubleML/doubleml-for-py
        path: doubleml-for-py
        ref: ${{ github.event.inputs.doubleml-py-branch }}

    - name: Install Python package
      run: |
        pip uninstall -y DoubleML
        cd doubleml-for-py
        pip install -e .[rdd]

    - name: Install R package DoubleML (main branch)
      if: ${{ github.event_name != 'workflow_dispatch' }}
      run: |
        Rscript -e "remotes::install_github('DoubleML/doubleml-for-r', dependencies = TRUE)"
      shell: bash
          
    - name: Install R package DoubleML (custom branch)
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        Rscript -e "remotes::install_github('DoubleML/doubleml-for-r@${{ github.event.inputs.doubleml-r-branch }}', dependencies = TRUE)"
      shell: bash

    - name: Build docu with sphinx
      run: |
        make -C doc html NBSPHINX_EXECUTE=${{ github.event.inputs.nbsphinx-execute || 'auto' }}

    - name: Check for broken links / URLs
      run: |
        make -C doc linkcheck

    - name: Upload html artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build_html
        path: doc/_build/html/
