.. include:: /guide/models/did/did_setup.rst


.. _did-pa-model:

Panel data
**********

.. include:: /guide/models/did/did_pa.rst


.. _did-cs-model:

Repeated cross-sections
***********************

.. note::
    Will be implemented soon.


.. _did-aggregation:

Effect Aggregation
******************


.. _did-binary-model:

Two treatment periods
*********************

.. note::
    This documentation refers the deprecated implementation for two time periods and is deprecated. We recommend using the implementation :ref:`did-pa-model` and :ref:`did-cs-model`.

.. include:: /guide/models/did/did_binary.rst
