.. include:: /guide/models/did/did_setup.rst


.. _did-pa-model:

Panel data
**********

.. include:: /guide/models/did/did_pa.rst


.. _did-cs-model:

Repeated cross-sections
***********************

.. include:: /guide/models/did/did_cs.rst


.. _did-aggregation:

Effect Aggregation
******************

.. include:: /guide/models/did/did_aggregation.rst


.. _did-binary-model:

Two treatment periods
*********************

.. warning::
    This documentation refers to the deprecated implementation for two time periods. 
    This functionality will be removed in a future version.

.. note::
    We recommend using the implementation :ref:`did-pa-model` and :ref:`did-cs-model`.

.. include:: /guide/models/did/did_binary.rst
